-- PowerPulse Complete Database Setup Script
-- Run this entire script in your Supabase SQL Editor to set up all tables and policies

-- ============================================
-- 1. PROFILES TABLE
-- ============================================
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text,
  monthly_budget_target numeric default 150,
  total_bill_amount numeric default 0,
  total_kwh_usage numeric default 0,
  expected_monthly_cost numeric default 0,
  updated_at timestamp with time zone
);

alter table profiles enable row level security;

drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);


-- ============================================
-- 2. APPLIANCES TABLE
-- ============================================
create table if not exists appliances (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  quantity integer default 1,
  watt numeric default 0,
  daily_usage_hours numeric default 0,
  peak_usage_hours numeric default 0,
  off_peak_usage_hours numeric default 0,
  usage_start_time time,
  usage_end_time time,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table appliances enable row level security;

drop policy if exists "Individuals can view their own appliances." on appliances;
create policy "Individuals can view their own appliances." on appliances
  for select using ((select auth.uid()) = user_id);

drop policy if exists "Individuals can insert their own appliances." on appliances;
create policy "Individuals can insert their own appliances." on appliances
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Individuals can update their own appliances." on appliances;
create policy "Individuals can update their own appliances." on appliances
  for update using ((select auth.uid()) = user_id);

drop policy if exists "Individuals can delete their own appliances." on appliances;
create policy "Individuals can delete their own appliances." on appliances
  for delete using ((select auth.uid()) = user_id);


-- ============================================
-- 3. PLANNING TABLE
-- ============================================
create table if not exists planning (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  plan_data jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Remove duplicates before adding unique constraint
delete from planning
where id not in (
  select max(id)
  from planning
  group by user_id
);

-- Add unique constraint if it doesn't exist
do $$
begin
  if not exists (
    select 1 from pg_constraint 
    where conname = 'planning_user_id_key'
  ) then
    alter table planning add constraint planning_user_id_key unique (user_id);
  end if;
end $$;

alter table planning enable row level security;

drop policy if exists "Users can view own plans" on planning;
create policy "Users can view own plans" on planning
  for select using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own plans" on planning;
create policy "Users can insert own plans" on planning
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own plans" on planning;
create policy "Users can update own plans" on planning
  for update using ((select auth.uid()) = user_id);
